name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: coveralls tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout pcb2gcode source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: show env twice?  no
      run: |
        env
        #echo "::set-env name=NODE_COVERALLS_DEBUG::1"
    - name: Upload coverage to coveralls
      id: my_upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: pcb2gcode-lcov.info
    - name: Upload coverage to coveralls again
      id: my_upload2
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: pcb2gcode-lcov.info
    - name: show the coveralls output
      continue-on-error: true
      run: |
        echo here is the result
        echo '${{ steps.my_upload.outputs.coveralls-api-result }}'
    - name: show the coveralls output2
      continue-on-error: true
      run: |
        echo here is the result
        echo '${{ steps.my_upload2.outputs.coveralls-api-result }}'
    - name: make a comment
      run: |
        sudo apt-get install jq
        echo "Making a comment"
        PAYLOAD=$(echo '{}' | jq --arg body "test comment from workflow" '.body = $body')
        echo $GITHUB_EVENT_PATH
        cat $GITHUB_EVENT_PATH
        COMMENTS_URL=$(cat $GITHUB_EVENT_PATH | jq -r .pull_request.comments_url)
        echo $PAYLOAD
        echo $COMMENTS_URL
        curl -v -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" --data "$PAYLOAD" "$COMMENTS_URL"
